### ISSUE TITLE
Return 200 on `/` path

### ISSUE THREAD

**Issue by alpe** [iov-one/iov-faucet#33]
I would like to enable [prometheus black box exporter](https://github.com/prometheus/blackbox_exporter)  probes for the endpoint. With other apps we return 200 on the root path. This is also the default config for the blackbox-exporter.

**Comment by alpe** [comment]
I can see your point in terms of api functionality but as the web is for humans, too you can see this as the landing page of your service. It is not uncommon to provide some basic info there like links to the endpoints, doc, etc. But that is not our technical requirement. To probe the ingress routes and monitor the service uptime a 200 response code would be sufficient.

**Comment by webmaster128** [comment]
okay, good, will create a short welcome page pointing to the README
