### ISSUE TITLE
Upgrade iov-faucet to iov-core 0.14

### ISSUE THREAD

**Issue by ethanfrey** [iov-one/iov-faucet#39]
We need to update the dependencies and ensure we use the default fees when sending tokens.

Pretty simple... just the issue of juggling the bilateral dependencies between iov-core tests and iov-faucet code.

Maybe we can just move the faucet client into iov-faucet as well and then we have a unidirectional dependency?

**Comment by webmaster128** [comment]
> Maybe we can just move the faucet client into iov-faucet as well and then we have a unidirectional dependency?

Yes. This requires some proper integration testing in this repo. Should be done but a bunch of work.
